"""
Unit tests for VideoReportService - Post-interview video analysis report generation.
Tests for:
- generate_report: full report generation with/without events
- _compute_scores: dimension scoring (emotion, posture, attention, overall)
- _format_report_prompt: LLM prompt formatting
- _generate_recommendations: LLM-based and fallback recommendation generation
"""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from src.services.video_report_service import VideoReportService


# ============================================================
# Fixtures
# ============================================================


@pytest.fixture
def mock_event_service():
    """Create a mock VideoEventService."""
    svc = AsyncMock()
    svc.aggregate_events = AsyncMock()
    svc.close = AsyncMock()
    return svc


@pytest.fixture
def service(mock_event_service):
    """Create a VideoReportService with mocked event service."""
    return VideoReportService(event_service=mock_event_service)


def _make_aggregated(**overrides) -> dict:
    """Build a sample aggregated result from VideoEventService.aggregate_events."""
    base = {
        "has_data": True,
        "dominant_emotion": "neutral",
        "emotion_scores": {"neutral": 0.6, "happy": 0.3, "sad": 0.1},
        "avg_posture_score": 85.0,
        "gaze_direction": "center",
        "avg_attention_score": 78.0,
        "recent_alerts": [
            {"type": "attention", "message": "Distracted"},
        ],
        "event_count": 50,
    }
    base.update(overrides)
    return base


# ============================================================
# generate_report
# ============================================================


class TestGenerateReport:
    """Test full report generation."""

    async def test_generate_report_with_events(self, service, mock_event_service):
        """Should generate a complete report when events are available."""
        mock_event_service.aggregate_events.return_value = _make_aggregated()

        # Mock LLM to return valid JSON
        mock_model = AsyncMock()
        mock_response = MagicMock()
        mock_response.content = json.dumps({
            "overall_impression": "面试者整体表现稳定。",
            "dimension_analysis": {
                "emotion": "情绪控制良好。",
                "posture": "姿态基本端正。",
                "attention": "注意力较为集中。",
            },
            "recommendations": ["保持良好的情绪管理", "注意坐姿"],
            "strengths": ["情绪稳定", "姿态端正"],
        })
        mock_model.call = AsyncMock(return_value=mock_response)

        with patch("src.services.video_report_service.select_model", return_value=mock_model):
            report = await service.generate_report("sess-123")

        assert report["session_id"] == "sess-123"
        assert "scores" in report
        assert "overall_impression" in report
        assert "recommendations" in report
        assert "strengths" in report

    async def test_generate_report_no_events(self, service, mock_event_service):
        """Should return empty report when no events available."""
        mock_event_service.aggregate_events.return_value = {"has_data": False}

        report = await service.generate_report("sess-empty")

        assert report["session_id"] == "sess-empty"
        assert report["has_data"] is False
        assert report["scores"] == {}
        assert report["recommendations"] == []

    async def test_generate_report_llm_fallback(self, service, mock_event_service):
        """Should fallback to rule-based scoring when LLM fails."""
        mock_event_service.aggregate_events.return_value = _make_aggregated()

        with patch("src.services.video_report_service.select_model", side_effect=Exception("LLM unavailable")):
            report = await service.generate_report("sess-llm-fail")

        assert report["session_id"] == "sess-llm-fail"
        assert "scores" in report
        assert "emotion_stability" in report["scores"]
        # Fallback should still have recommendations generated by rules
        assert isinstance(report["recommendations"], list)

    async def test_generate_report_llm_returns_invalid_json(self, service, mock_event_service):
        """Should fallback when LLM returns non-JSON response."""
        mock_event_service.aggregate_events.return_value = _make_aggregated()

        mock_model = AsyncMock()
        mock_response = MagicMock()
        mock_response.content = "This is not valid JSON"
        mock_model.call = AsyncMock(return_value=mock_response)

        with patch("src.services.video_report_service.select_model", return_value=mock_model):
            report = await service.generate_report("sess-bad-json")

        assert report["session_id"] == "sess-bad-json"
        assert "scores" in report
        assert isinstance(report["recommendations"], list)


# ============================================================
# _compute_scores
# ============================================================


class TestComputeScores:
    """Test dimension score computation."""

    def test_compute_scores_all_dimensions(self, service):
        """Should compute all four dimension scores."""
        aggregated = _make_aggregated(
            emotion_scores={"neutral": 0.6, "happy": 0.3, "sad": 0.1},
            avg_posture_score=85.0,
            avg_attention_score=78.0,
        )
        scores = service._compute_scores(aggregated)

        assert "emotion_stability" in scores
        assert "posture" in scores
        assert "attention" in scores
        assert "overall" in scores

    def test_compute_scores_emotion_stability(self, service):
        """Emotion stability should be higher when one emotion dominates."""
        # Neutral dominates -> high stability
        stable = _make_aggregated(emotion_scores={"neutral": 0.9, "happy": 0.05, "sad": 0.05})
        scores_stable = service._compute_scores(stable)

        # Mixed emotions -> lower stability
        mixed = _make_aggregated(emotion_scores={"happy": 0.33, "sad": 0.33, "angry": 0.34})
        scores_mixed = service._compute_scores(mixed)

        assert scores_stable["emotion_stability"] > scores_mixed["emotion_stability"]

    def test_compute_scores_posture_uses_average(self, service):
        """Posture score should directly use avg_posture_score."""
        aggregated = _make_aggregated(avg_posture_score=92.0)
        scores = service._compute_scores(aggregated)
        assert scores["posture"] == 92.0

    def test_compute_scores_attention_uses_average(self, service):
        """Attention score should directly use avg_attention_score."""
        aggregated = _make_aggregated(avg_attention_score=65.0)
        scores = service._compute_scores(aggregated)
        assert scores["attention"] == 65.0

    def test_compute_scores_overall_weighted(self, service):
        """Overall score should be 0.3*emotion + 0.3*posture + 0.4*attention."""
        aggregated = _make_aggregated(
            emotion_scores={"neutral": 0.9, "happy": 0.1},
            avg_posture_score=80.0,
            avg_attention_score=70.0,
        )
        scores = service._compute_scores(aggregated)

        expected = 0.3 * scores["emotion_stability"] + 0.3 * 80.0 + 0.4 * 70.0
        assert abs(scores["overall"] - round(expected, 1)) < 0.5

    def test_compute_scores_missing_posture(self, service):
        """Missing posture score should default to a reasonable value."""
        aggregated = _make_aggregated(avg_posture_score=None)
        scores = service._compute_scores(aggregated)
        # Should still have a valid score (e.g. 70 as default)
        assert scores["posture"] == 70.0

    def test_compute_scores_missing_attention(self, service):
        """Missing attention score should default to a reasonable value."""
        aggregated = _make_aggregated(avg_attention_score=None)
        scores = service._compute_scores(aggregated)
        assert scores["attention"] == 70.0

    def test_compute_scores_empty_emotions(self, service):
        """Empty emotion scores should default to moderate stability."""
        aggregated = _make_aggregated(emotion_scores={})
        scores = service._compute_scores(aggregated)
        assert scores["emotion_stability"] == 70.0


# ============================================================
# _format_report_prompt
# ============================================================


class TestFormatReportPrompt:
    """Test LLM prompt formatting."""

    def test_prompt_contains_scores(self, service):
        """Prompt should include all dimension scores."""
        scores = {"emotion_stability": 85, "posture": 90, "attention": 75, "overall": 82}
        aggregated = _make_aggregated()

        prompt = service._format_report_prompt(scores, aggregated)

        assert "85" in prompt
        assert "90" in prompt
        assert "75" in prompt
        assert "82" in prompt

    def test_prompt_requests_json_output(self, service):
        """Prompt should request JSON output format."""
        scores = {"emotion_stability": 80, "posture": 80, "attention": 80, "overall": 80}
        aggregated = _make_aggregated()

        prompt = service._format_report_prompt(scores, aggregated)

        assert "JSON" in prompt.upper() or "json" in prompt

    def test_prompt_contains_emotion_details(self, service):
        """Prompt should include dominant emotion and emotion distribution."""
        scores = {"emotion_stability": 80, "posture": 80, "attention": 80, "overall": 80}
        aggregated = _make_aggregated(
            dominant_emotion="happy",
            emotion_scores={"happy": 0.7, "neutral": 0.3},
        )

        prompt = service._format_report_prompt(scores, aggregated)

        assert "happy" in prompt

    def test_prompt_contains_alerts(self, service):
        """Prompt should include alert information."""
        scores = {"emotion_stability": 80, "posture": 80, "attention": 80, "overall": 80}
        aggregated = _make_aggregated(
            recent_alerts=[{"type": "gaze", "message": "Looking away"}],
        )

        prompt = service._format_report_prompt(scores, aggregated)

        assert "Looking away" in prompt


# ============================================================
# _generate_recommendations (fallback)
# ============================================================


class TestGenerateRecommendations:
    """Test fallback recommendation generation."""

    def test_recommendations_low_attention(self, service):
        """Low attention score should generate attention-related recommendation."""
        scores = {"emotion_stability": 80, "posture": 80, "attention": 40, "overall": 60}
        aggregated = _make_aggregated()

        recs = service._generate_rule_based_recommendations(scores, aggregated)

        assert any("注意力" in r for r in recs)

    def test_recommendations_low_posture(self, service):
        """Low posture score should generate posture-related recommendation."""
        scores = {"emotion_stability": 80, "posture": 50, "attention": 80, "overall": 70}
        aggregated = _make_aggregated()

        recs = service._generate_rule_based_recommendations(scores, aggregated)

        assert any("姿态" in r or "坐姿" in r for r in recs)

    def test_recommendations_low_emotion_stability(self, service):
        """Low emotion stability should generate emotion-related recommendation."""
        scores = {"emotion_stability": 40, "posture": 80, "attention": 80, "overall": 68}
        aggregated = _make_aggregated()

        recs = service._generate_rule_based_recommendations(scores, aggregated)

        assert any("情绪" in r for r in recs)

    def test_recommendations_high_scores(self, service):
        """High scores should generate positive recommendations."""
        scores = {"emotion_stability": 95, "posture": 95, "attention": 95, "overall": 95}
        aggregated = _make_aggregated()

        recs = service._generate_rule_based_recommendations(scores, aggregated)

        assert len(recs) > 0
        # Should have positive suggestions
        assert any("保持" in r or "继续" in r for r in recs)

    def test_recommendations_returns_list(self, service):
        """Should always return a list."""
        scores = {"emotion_stability": 80, "posture": 80, "attention": 80, "overall": 80}
        aggregated = _make_aggregated()

        recs = service._generate_rule_based_recommendations(scores, aggregated)

        assert isinstance(recs, list)
        assert len(recs) >= 1
